version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: deep-recall-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deep_recall
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init_embeddings_tables.sql:/docker-entrypoint-initdb.d/init_embeddings_tables.sql
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
    driver: local 