apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: prod-

commonLabels:
  environment: production
  registry: prod-registry.example.com
  tag: stable

patchesStrategicMerge:
- patches/inference-deployment-patch.yaml
- patches/inference-hpa-patch.yaml

images:
- name: ${REGISTRY}/deep-recall/inference-optimized
  newName: prod-registry.example.com/deep-recall/inference-optimized
  newTag: stable 