apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml

namespace: deep-recall

namePrefix: prod-

commonLabels:
  environment: prod
  registry: prod-registry.example.com/
  tag: stable

replicas:
- name: deep-recall-memory
  count: 2
- name: deep-recall-inference
  count: 2
- name: deep-recall-orchestrator
  count: 2

patches:
- path: patches/inference-deployment-gpu.yaml
- path: patches/memory-deployment-prod.yaml
- path: patches/orchestrator-deployment-prod.yaml

configMapGenerator:
- name: deep-recall-config
  behavior: merge
  literals:
  - LOG_LEVEL=INFO

images:
- name: ${REGISTRY}/deep-recall/inference-optimized
  newName: prod-registry.example.com/deep-recall/inference-optimized
  newTag: stable 