version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg16
    container_name: recall-memories-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recall_memories_db
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ../../
      dockerfile: examples/streamlit-memories/Dockerfile.fix
    container_name: recall-memories-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=recall_memories_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - API_HOST=0.0.0.0
      - API_PORT=8404
    ports:
      - "8404:8404"
    volumes:
      - ../../examples/streamlit-memories:/app
      - ../../memory:/app/memory

volumes:
  pgdata: 