global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "inference_service"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["inference-service:8000"]
    
  - job_name: "memory_service"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["memory-service:8000"]
    
  - job_name: "orchestrator"
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ["orchestrator:8001"]

  - job_name: "node_exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"] 