apiVersion: apps/v1
kind: Deployment
metadata:
  name: deep-recall-memory
spec:
  template:
    spec:
      containers:
      - name: memory-service
        resources:
          limits:
            cpu: "2"
            memory: 4Gi
          requests:
            cpu: "1"
            memory: 2Gi 