apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: deep-recall-dev

commonLabels:
  environment: dev
  registry: dev-registry.example.com/
  tag: latest

patches:
- path: patches/inference-deployment-cpu.yaml
- path: patches/memory-deployment-dev.yaml
- path: patches/orchestrator-deployment-dev.yaml

configMapGenerator:
- name: deep-recall-config
  behavior: merge
  literals:
  - LOG_LEVEL=DEBUG

namePrefix: dev-

commonLabels:
  environment: development
  registry: dev-registry.example.com
  tag: latest

patchesStrategicMerge:
- patches/inference-deployment-patch.yaml
- patches/inference-hpa-patch.yaml

images:
- name: ${REGISTRY}/deep-recall/inference-optimized
  newName: dev-registry.example.com/deep-recall/inference-optimized
  newTag: latest 