apiVersion: apps/v1
kind: Deployment
metadata:
  name: deep-recall-orchestrator
spec:
  template:
    spec:
      containers:
      - name: orchestrator
        env:
        - name: LOG_LEVEL
          value: DEBUG
        resources:
          limits:
            cpu: "500m"
            memory: 1Gi
          requests:
            cpu: "250m"
            memory: 512Mi 