apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- inference-deployment.yaml
- inference-hpa.yaml
- model-cache-pvc.yaml
- custom-metrics-adapter.yaml
- memory-service.yaml
- orchestrator-service.yaml
- configmap.yaml
- prometheus.yaml
- grafana.yaml

commonLabels:
  app: deep-recall
  environment: base

configMapGenerator:
- name: deep-recall-config
  files:
  - model_config.yaml=config/model_config.yaml
  - logging_config.yaml=config/logging_config.yaml

# Variables will be substituted in the resource files
vars:
- name: REGISTRY
  objref:
    kind: Deployment
    name: deep-recall-inference
    apiVersion: apps/v1
  fieldref:
    fieldpath: metadata.labels.registry
- name: TAG
  objref:
    kind: Deployment
    name: deep-recall-inference
    apiVersion: apps/v1
  fieldref:
    fieldpath: metadata.labels.tag 