apiVersion: apps/v1
kind: Deployment
metadata:
  name: deep-recall-memory
  labels:
    app: deep-recall
    component: memory-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deep-recall
      component: memory-service
  template:
    metadata:
      labels:
        app: deep-recall
        component: memory-service
    spec:
      containers:
      - name: memory-service
        image: $(REGISTRY)/deep-recall-memory:$(TAG)
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: DATABASE_URL
          value: postgresql://deep_recall:deep_recall_password@deep-recall-postgresql/deep_recall
        - name: VECTOR_DB_URL
          value: http://deep-recall-qdrant:6333
        - name: LOG_LEVEL
          value: INFO
        - name: PYTHONPATH
          value: /app
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          limits:
            cpu: 1
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: deep-recall-config
---
apiVersion: v1
kind: Service
metadata:
  name: deep-recall-memory
  labels:
    app: deep-recall
    component: memory-service
spec:
  type: ClusterIP
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: deep-recall
    component: memory-service 